// このファイルは「設定」タブの「サンプルを読み込む」で使用する初期データ。
// ユーザー本人の記述をそのまま構造化したもの。不要になったら自由に編集・削除してください。
// attribution: 本人 / 他者 / 環境 / 複合
// controllability: 可 / 部分的 / 不可
// timeFrame: 過去 / 現在 / 未来
// depth: 表層 / 中層 / 核心
window.SAMPLE_SEEDS = [
  {
    title: '人の幸せを喜べない',
    category: '幸せ・比較',
    intensity: 8,
    tags: ['嫉妬', '比較', '自己'],
    description: '人の幸せを喜べない。\nそれは、本当は自分もやりたいのにできていない、やっていないから。できていない自分を本当は気にしているから。',
    insight: 'それは今、できないこともある。できるけど意地を張っていることもある。できるけど余裕がないこともある。',
    attribution: '本人',
    controllability: '部分的',
    timeFrame: '現在',
    depth: '中層',
  },

  // --- 年齢と経験に関する苦しみ ---
  {
    title: '苦しんだ時間 vs 手に入れてきた人への憎しみ',
    category: '年齢と経験',
    intensity: 9,
    tags: ['嫉妬', '憎しみ', '時間'],
    description: '私が苦しみの中過ごした時間を、ほしいもの手に入れながら過ごしてる人は憎い、いつか不幸になれ。\n情報もお金も友達も。',
    insight: '',
    attribution: '複合',
    controllability: '不可',
    timeFrame: '過去',
    depth: '中層',
  },
  {
    title: '努力しない人への軽蔑と、そう思う自分への嫌悪',
    category: '年齢と経験',
    intensity: 8,
    tags: ['軽蔑', '自己嫌悪', '正当化'],
    description: '努力できない遊んでるやつは中身が空っぽ、人の真似しかできない、可哀想にね。\nそう思う自分は醜い、けれど、そうしなければ私のこれまでは正当化されない。',
    insight: '',
    attribution: '本人',
    controllability: '部分的',
    timeFrame: '現在',
    depth: '中層',
  },
  {
    title: '比較構造の中で「勝つ」と言いながら疲れている',
    category: '年齢と経験',
    intensity: 7,
    tags: ['比較', '勝負', '疲労'],
    description: '本当は因果関係はない、でも君が比較構造を作った、私は勝つ。\nでももう勝負に疲れてる、正直面倒、何度も言うけど因果関係はない、別れれば全て消える話なの。\n絶縁なんてしてくれないでしょう。',
    insight: '人間関係に関する苦しみも含んでる。',
    attribution: '複合',
    controllability: '部分的',
    timeFrame: '現在',
    depth: '中層',
  },
  {
    title: '「いい人」でいる努力と、一瞬で湧き上がる憎悪',
    category: '年齢と経験',
    intensity: 9,
    tags: ['二面性', '憎悪', '葛藤'],
    description: '私なりに、いい人になる努力はしてる。\n死んで？\nものの瞬間で気持ちを踏みにじってくる憎悪、一方、それだけの覚悟とも言えるね。\nなんで？憎い、なんで消えてくれないの？\n大人しく遠くに行ってよ。',
    insight: '',
    attribution: '本人',
    controllability: '部分的',
    timeFrame: '現在',
    depth: '核心',
  },
  {
    title: 'さっきまで祝っていたのに、もう別れたい',
    category: '年齢と経験',
    intensity: 9,
    tags: ['関係', '抜け道', '後悔'],
    description: 'さっきまで祝ってたのに、もう別れたい、克服できる気がしない、私が悪いんでしょ、なんで世の中は抜け道を作るの、ずるい、話を聞かなければよかった。',
    insight: '',
    attribution: '複合',
    controllability: '部分的',
    timeFrame: '現在',
    depth: '中層',
  },

  // --- 人間関係に関する苦しみ ---
  {
    title: '人に心を開ききれない／悪口を言われている気がする',
    category: '人間関係',
    intensity: 8,
    tags: ['孤独', '不信', '自己否定'],
    description: '人に心を開ききれない、常に嫌われてると思ってる、周囲で話をしている人達はみんな私の悪口を言っていると思っている。',
    insight: '本当のことは分からない。',
    attribution: '本人',
    controllability: '部分的',
    timeFrame: '現在',
    depth: '中層',
  },
  {
    title: '家族からの扱いが私を形成した',
    category: '人間関係',
    intensity: 9,
    tags: ['家族', '幼少期', 'ルーツ'],
    description: '家族からの扱いが私を形成した。\n他の子供との比較構造、話を最後まで聞いて貰えない、欲しいものを言うことは許されない、否定。',
    insight: '',
    attribution: '他者',
    controllability: '不可',
    timeFrame: '過去',
    depth: '核心',
  },

  // --- 外見に関する苦しみ ---
  {
    title: '外見への執着は完全に自己満',
    category: '外見',
    intensity: 5,
    tags: ['自己満', 'モテ'],
    description: '完全に自己満。\n「モテたい」でないのは確か。だって現状の私でも、君は受け止めてくれてる。',
    insight: '',
    attribution: '本人',
    controllability: '可',
    timeFrame: '現在',
    depth: '表層',
  },
  {
    title: 'できない理由1: 人目／相手でキャラを変える',
    category: '外見',
    intensity: 6,
    tags: ['人目', 'キャラ使い分け'],
    description: 'できない理由1：人目を気にしているから。\n私は相手によって見せるキャラを変えてる。相手に見せられないキャラは隠してる。',
    insight: '',
    attribution: '本人',
    controllability: '部分的',
    timeFrame: '現在',
    depth: '中層',
  },
  {
    title: 'できない理由2: キャラ被り回避／先をゆく',
    category: '外見',
    intensity: 5,
    tags: ['キャラ', '差別化'],
    description: 'できない理由2：キャラ被りしたくないから。意識的に。もしくは、先をゆく。',
    insight: '',
    attribution: '本人',
    controllability: '可',
    timeFrame: '現在',
    depth: '中層',
  },
  {
    title: '圧倒的になるための準備中（本当の私は知られていない）',
    category: '外見',
    intensity: 5,
    tags: ['準備', '自己変革', '秘密'],
    description: '今から私は圧倒的になるの。その為に準備してるの。みんな、本当の私の事を知らなくて残念ね。',
    insight: '',
    attribution: '本人',
    controllability: '可',
    timeFrame: '未来',
    depth: '中層',
  },

  // --- 解決に向かうため ---
  {
    title: '本当はやりたかったことをやる',
    category: '解決に向けて',
    intensity: 3,
    tags: ['行動', '自己一致'],
    description: '本当はやりたかったことをやればいい。',
    insight: '',
    attribution: '本人',
    controllability: '可',
    timeFrame: '未来',
    depth: '表層',
  },
  {
    title: '強がっていた・けれど苦しんでいた自分を受け止める・許す',
    category: '解決に向けて',
    intensity: 3,
    tags: ['自己受容', '許し'],
    description: 'ずっと強がっていた、でも確かに苦しんでいた自分を受け止める。許す。',
    insight: '',
    attribution: '本人',
    controllability: '可',
    timeFrame: '現在',
    depth: '核心',
  },
  {
    title: '比較ではない場所／別レイヤーへ',
    category: '解決に向けて',
    intensity: 3,
    tags: ['別レイヤー', '脱比較'],
    description: '比較ではない場所に行く。別レイヤー。',
    insight: '',
    attribution: '本人',
    controllability: '可',
    timeFrame: '未来',
    depth: '中層',
  },
];

// 理由ネットワークのサンプル。
// seedTitle: 上のサンプル記録の title と一致していると、その記録に紐付く。
// parents: 他の理由の key を指定すると「より深い理由」として繋がる（図解で破線）。
window.SAMPLE_REASONS = [
  {
    key: 'R_root_family',
    text: '家族との比較構造・否定の中で育ったから',
  },
  {
    key: 'R_self_worth_by_effort',
    text: '努力した分だけ価値がある、という信念',
    parents: ['R_root_family'],
  },
  {
    key: 'R_past_justification',
    text: '苦しんできた過去を意味あるものにしたい',
    parents: ['R_self_worth_by_effort'],
  },
  {
    key: 'R_fear_rejected',
    text: '本当の自分を出すと嫌われる／拒絶される恐れ',
    parents: ['R_root_family'],
  },
  {
    key: 'R_char_switch',
    text: '相手によって見せるキャラを変える習慣',
    parents: ['R_fear_rejected'],
  },

  // 紐付け
  {
    seedTitle: '人の幸せを喜べない',
    axisKey: '',
    text: '自分もやりたいのに、できていない／やっていないことを気にしているから',
    parents: ['R_self_worth_by_effort'],
  },
  {
    seedTitle: '苦しんだ時間 vs 手に入れてきた人への憎しみ',
    axisKey: 'attribution',
    text: '同じ時間を過ごしたのに、得ているものが違いすぎるのが不公平に感じる',
    parents: ['R_past_justification'],
  },
  {
    seedTitle: '努力しない人への軽蔑と、そう思う自分への嫌悪',
    axisKey: '',
    text: 'そう思わないと、これまでの自分の選択が無価値に見えてしまう',
    parents: ['R_past_justification', 'R_self_worth_by_effort'],
  },
  {
    seedTitle: '比較構造の中で「勝つ」と言いながら疲れている',
    axisKey: '',
    text: '本当は勝負に意味はないと分かっているが、降りる許可が自分に出せない',
    parents: ['R_self_worth_by_effort'],
  },
  {
    seedTitle: '人に心を開ききれない／悪口を言われている気がする',
    axisKey: 'depth',
    text: '人は私を見たら否定するはず、という前提が染み付いている',
    parents: ['R_fear_rejected', 'R_root_family'],
  },
  {
    seedTitle: '家族からの扱いが私を形成した',
    axisKey: 'depth',
    text: '比較・否定・聞いてもらえなかった経験が基盤になっている',
    parents: ['R_root_family'],
  },
  {
    seedTitle: 'できない理由1: 人目／相手でキャラを変える',
    axisKey: '',
    text: '本当の自分を見せると嫌われるかもしれない',
    parents: ['R_fear_rejected', 'R_char_switch'],
  },
  {
    seedTitle: 'できない理由2: キャラ被り回避／先をゆく',
    axisKey: '',
    text: '人と同じでは埋もれる／価値が無い、という不安',
    parents: ['R_self_worth_by_effort', 'R_char_switch'],
  },
  {
    seedTitle: '圧倒的になるための準備中（本当の私は知られていない）',
    axisKey: '',
    text: '今の自分では不十分で、圧倒的にならないと肯定されないという信念',
    parents: ['R_self_worth_by_effort', 'R_fear_rejected'],
  },
  {
    seedTitle: '強がっていた・けれど苦しんでいた自分を受け止める・許す',
    axisKey: 'depth',
    text: '強がらなくてもここにいていい、という許可を自分に出す',
    parents: [],
  },
  {
    seedTitle: '比較ではない場所／別レイヤーへ',
    axisKey: '',
    text: '同じ土俵にいる限り終わらない。別の評価軸の場所に移ることで勝負そのものから降りられる',
    parents: [],
  },
];

// 議事録／対話ログのサンプル。sections は順序通り。
// section の linkSeedTitles / linkReasonKeys は、該当する seed / reason に自動紐付けされる（存在すれば）。
window.SAMPLE_SESSIONS = [
  {
    title: 'パートナーとの議事録 — 劣等感と層構造の発見',
    date: '2026-04-18',
    participants: ['私（悩みを抱えている側）', '俺（相談を受けている側、パートナー）'],
    sections: [
      {
        heading: '1. 劣等感の構造の発見',
        body: '劣等感を解消するために行動してきたが、解消されない原因に気づいた。行動の動機が「相手に勝ちたい」「追いつきたい」にあるため、判断軸が相手との比較の中にあり、どれだけ自分が成長しても苦しみが消えない。相手も進むので追いついても並んだだけ、抜いても相手が先に進めばまた負ける構造。',
        linkSeedTitles: ['比較構造の中で「勝つ」と言いながら疲れている'],
        linkReasonKeys: ['R_self_worth_by_effort'],
      },
      {
        heading: '2. 「ずらす」選択の落とし穴',
        body: '比較から降りるために違う道を選んできた。しかし相手が自分のやりたいことをやっているのを見て悔しくなる。本当は同じ道（スーツ）がやりたいのに、被りたくなくてずらしていた。「被る=負ける」の前提が劣等感の核にあった。',
        linkSeedTitles: ['できない理由2: キャラ被り回避／先をゆく'],
        linkReasonKeys: ['R_char_switch'],
      },
      {
        heading: '3. 積み上げの所在',
        body: '議論の過程で立場を整理した。私は積み上げてきた側ではなく、環境的理由で積み上げてこられなかった側。ゼロから始めようとしている時に、すでに積み上げている人が目の前にいる状況。',
        linkSeedTitles: ['苦しんだ時間 vs 手に入れてきた人への憎しみ'],
        linkReasonKeys: [],
      },
      {
        heading: '4. 「始めたい」の所有権',
        body: 'やりたい気持ちは元々あった。「私なんか」という自己否定と、環境的な不可能性で押し込めてきた。今は環境が変わって可能になったが、押し込める癖が残っていた。相手を見て蓋が外れた。相手は敵ではなく、蓋を外してくれた存在。',
        linkSeedTitles: [],
        linkReasonKeys: ['R_fear_rejected'],
      },
      {
        heading: '5. 悲しみの正体',
        body: '追いつけないのではなく、「あの時の自分でやりたかった」が本質。比較の苦しみではなく、喪失の悲しみ。押し込めてきた時間は戻らない。この悲しみは完全には消えない。消そうとせず、悲しみを抱えたまま始める選択が必要。',
        linkSeedTitles: [],
        linkReasonKeys: [],
      },
      {
        heading: '6. パートナーとの関係',
        body: '比較を想起させる存在は彼。ただし彼に比較の意図はなく、共通の話題として話したかっただけ。彼には「その話題がきつい」と伝えてあり、彼は配慮してくれている。それでも目に入る時は入る。',
        linkSeedTitles: [],
        linkReasonKeys: [],
      },
      {
        heading: '7. 苦しみの層構造',
        body: '層A: 「ありのままでは愛されない」という幼少期からの信念\n層B: 比較・自己否定・欲求の抑圧という思考と行動の癖\n層C: 外見、人間関係、始めるのが遅いという具体的な悩み\n解決すべきは層A。CだけつぶしてもCが再生産される。',
        linkSeedTitles: ['家族からの扱いが私を形成した'],
        linkReasonKeys: ['R_root_family', 'R_fear_rejected'],
      },
      {
        heading: '8. 家庭的背景',
        body: '「勉強しないと見捨てられる」という感覚の中で育った。遊びや情報アクセス、友人関係が制限された。当時は辛いと思わないようにしていた。押し込めてきた感情の蓋が開き始めた段階。',
        linkSeedTitles: ['家族からの扱いが私を形成した'],
        linkReasonKeys: ['R_root_family'],
      },
      {
        heading: '9. 解決アプローチの方針',
        body: '感情論や気合ではなく、構造で変える方向で合意。\n層Aを維持するループ：入力 → 解釈 → 感情 → 行動 → 結果 → 信念強化\n5つの介入点：\n・入力の制御\n・解釈の遅延\n・感情から行動への切断\n・行動の固定\n・結果の再定義',
        linkSeedTitles: [],
        linkReasonKeys: [],
      },
      {
        heading: '10. 存在実感の育て方',
        body: '「存在していい」(許可ベース)から「存在している」(事実ベース)への転換。\n3つの経路：\n・身体経路（感覚の名指し、身体を動かす、五感の強化）\n・痕跡経路（行動記録、物理的痕跡、空間の個人化）\n・関係経路（応答のある関係、応答する側に立つ、植物やペット）',
        linkSeedTitles: [],
        linkReasonKeys: [],
      },
      {
        heading: '11. 今すぐの気づき',
        body: 'すべての苦しみは「今ここにいる自分を自分で許可していない」に帰着する。層Aは解体するものではなく、気づいた瞬間に同化が解ける。信念を持っている主体は信念そのものではない。自分の苦しみを構造化し、分析し、設計できる時点で、すでに層Aの外側に立てている。',
        linkSeedTitles: ['強がっていた・けれど苦しんでいた自分を受け止める・許す'],
        linkReasonKeys: [],
      },
      {
        heading: '12. パートナーとの関係の再整理',
        body: '彼は向き合う覚悟を表明している。ただし問題点が2つ。\n・トラウマが彼との関係に紐づいている（彼個人の問題ではなく、関係の中で発動する）\n・配慮されることで、以前のフラットな関係が失われている',
        linkSeedTitles: [],
        linkReasonKeys: [],
      },
      {
        heading: '13. 関係の構造再設計',
        body: '彼の側から見た設計として、以下が出た。\n・役割の非固定化（ケアする側とされる側を固定しない）\n・問題の外在化（問題を二人の間のテーブルに置く）\n・配慮の言語化（隠れた配慮を透明にする）\n・定期的なメンテナンス時間\n・彼自身の限界の可視化と自己ケア経路の確保',
        linkSeedTitles: [],
        linkReasonKeys: [],
      },
      {
        heading: '14. 根本的な構造的相性',
        body: '彼自身が私の劣等感の対象そのもの。色々できて、早く始めていて、遊んできて、温かい家族を持つ。私が押し込めてきたものを全部持っている存在。これは配慮では解決しない、存在レベルの相性問題。',
        linkSeedTitles: [],
        linkReasonKeys: [],
      },
      {
        heading: '15. 治癒環境としての彼',
        body: '彼はトリガーであると同時に、私にとっての治癒経路でもある。彼の家族の温かさは私の理想像。彼と関わることで過去の環境から抜け出せる可能性がある。長期的には関係を続けたい。一時的な距離は運用として使える。',
        linkSeedTitles: [],
        linkReasonKeys: [],
      },
      {
        heading: '16. 4つの設計課題（これから詰める）',
        body: '・彼を手段化しないための区別（← 現在ここ）\n・彼の家族との関わり方の設計\n・治癒経路の複数化\n・一時的距離のルール設計',
        linkSeedTitles: [],
        linkReasonKeys: [],
      },
      {
        heading: '17. 現在進行中',
        body: '1の「手段化しないための区別」について、動機を2つに分ける作業を提示中。\n動機A: 彼個人への愛情・関心（彼だから一緒にいたい理由）\n動機B: 彼を通じて得られる経験への欲求（彼の環境だから欲しい理由）\nそれぞれ3つずつ書き出す作業を依頼したところ。',
        linkSeedTitles: [],
        linkReasonKeys: [],
      },
    ],
  },
];


