// このファイルは「設定」タブの「サンプルを読み込む」で使用する初期データ。
// ユーザー本人の記述をそのまま構造化したもの。不要になったら自由に編集・削除してください。
// attribution: 本人 / 他者 / 環境 / 複合
// controllability: 可 / 部分的 / 不可
// timeFrame: 過去 / 現在 / 未来
// depth: 表層 / 中層 / 核心
window.SAMPLE_SEEDS = [
  {
    title: '人の幸せを喜べない',
    category: '幸せ・比較',
    intensity: 8,
    tags: ['嫉妬', '比較', '自己'],
    description: '人の幸せを喜べない。\nそれは、本当は自分もやりたいのにできていない、やっていないから。できていない自分を本当は気にしているから。',
    insight: 'それは今、できないこともある。できるけど意地を張っていることもある。できるけど余裕がないこともある。',
    attribution: '本人',
    controllability: '部分的',
    timeFrame: '現在',
    depth: '中層',
  },

  // --- 年齢と経験に関する苦しみ ---
  {
    title: '苦しんだ時間 vs 手に入れてきた人への憎しみ',
    category: '年齢と経験',
    intensity: 9,
    tags: ['嫉妬', '憎しみ', '時間'],
    description: '私が苦しみの中過ごした時間を、ほしいもの手に入れながら過ごしてる人は憎い、いつか不幸になれ。\n情報もお金も友達も。',
    insight: '',
    attribution: '複合',
    controllability: '不可',
    timeFrame: '過去',
    depth: '中層',
  },
  {
    title: '努力しない人への軽蔑と、そう思う自分への嫌悪',
    category: '年齢と経験',
    intensity: 8,
    tags: ['軽蔑', '自己嫌悪', '正当化'],
    description: '努力できない遊んでるやつは中身が空っぽ、人の真似しかできない、可哀想にね。\nそう思う自分は醜い、けれど、そうしなければ私のこれまでは正当化されない。',
    insight: '',
    attribution: '本人',
    controllability: '部分的',
    timeFrame: '現在',
    depth: '中層',
  },
  {
    title: '比較構造の中で「勝つ」と言いながら疲れている',
    category: '年齢と経験',
    intensity: 7,
    tags: ['比較', '勝負', '疲労'],
    description: '本当は因果関係はない、でも君が比較構造を作った、私は勝つ。\nでももう勝負に疲れてる、正直面倒、何度も言うけど因果関係はない、別れれば全て消える話なの。\n絶縁なんてしてくれないでしょう。',
    insight: '人間関係に関する苦しみも含んでる。',
    attribution: '複合',
    controllability: '部分的',
    timeFrame: '現在',
    depth: '中層',
  },
  {
    title: '「いい人」でいる努力と、一瞬で湧き上がる憎悪',
    category: '年齢と経験',
    intensity: 9,
    tags: ['二面性', '憎悪', '葛藤'],
    description: '私なりに、いい人になる努力はしてる。\n死んで？\nものの瞬間で気持ちを踏みにじってくる憎悪、一方、それだけの覚悟とも言えるね。\nなんで？憎い、なんで消えてくれないの？\n大人しく遠くに行ってよ。',
    insight: '',
    attribution: '本人',
    controllability: '部分的',
    timeFrame: '現在',
    depth: '核心',
  },
  {
    title: 'さっきまで祝っていたのに、もう別れたい',
    category: '年齢と経験',
    intensity: 9,
    tags: ['関係', '抜け道', '後悔'],
    description: 'さっきまで祝ってたのに、もう別れたい、克服できる気がしない、私が悪いんでしょ、なんで世の中は抜け道を作るの、ずるい、話を聞かなければよかった。',
    insight: '',
    attribution: '複合',
    controllability: '部分的',
    timeFrame: '現在',
    depth: '中層',
  },

  // --- 人間関係に関する苦しみ ---
  {
    title: '人に心を開ききれない／悪口を言われている気がする',
    category: '人間関係',
    intensity: 8,
    tags: ['孤独', '不信', '自己否定'],
    description: '人に心を開ききれない、常に嫌われてると思ってる、周囲で話をしている人達はみんな私の悪口を言っていると思っている。',
    insight: '本当のことは分からない。',
    attribution: '本人',
    controllability: '部分的',
    timeFrame: '現在',
    depth: '中層',
  },
  {
    title: '家族からの扱いが私を形成した',
    category: '人間関係',
    intensity: 9,
    tags: ['家族', '幼少期', 'ルーツ'],
    description: '家族からの扱いが私を形成した。\n他の子供との比較構造、話を最後まで聞いて貰えない、欲しいものを言うことは許されない、否定。',
    insight: '',
    attribution: '他者',
    controllability: '不可',
    timeFrame: '過去',
    depth: '核心',
  },

  // --- 外見に関する苦しみ ---
  {
    title: '外見への執着は完全に自己満',
    category: '外見',
    intensity: 5,
    tags: ['自己満', 'モテ'],
    description: '完全に自己満。\n「モテたい」でないのは確か。だって現状の私でも、君は受け止めてくれてる。',
    insight: '',
    attribution: '本人',
    controllability: '可',
    timeFrame: '現在',
    depth: '表層',
  },
  {
    title: 'できない理由1: 人目／相手でキャラを変える',
    category: '外見',
    intensity: 6,
    tags: ['人目', 'キャラ使い分け'],
    description: 'できない理由1：人目を気にしているから。\n私は相手によって見せるキャラを変えてる。相手に見せられないキャラは隠してる。',
    insight: '',
    attribution: '本人',
    controllability: '部分的',
    timeFrame: '現在',
    depth: '中層',
  },
  {
    title: 'できない理由2: キャラ被り回避／先をゆく',
    category: '外見',
    intensity: 5,
    tags: ['キャラ', '差別化'],
    description: 'できない理由2：キャラ被りしたくないから。意識的に。もしくは、先をゆく。',
    insight: '',
    attribution: '本人',
    controllability: '可',
    timeFrame: '現在',
    depth: '中層',
  },
  {
    title: '圧倒的になるための準備中（本当の私は知られていない）',
    category: '外見',
    intensity: 5,
    tags: ['準備', '自己変革', '秘密'],
    description: '今から私は圧倒的になるの。その為に準備してるの。みんな、本当の私の事を知らなくて残念ね。',
    insight: '',
    attribution: '本人',
    controllability: '可',
    timeFrame: '未来',
    depth: '中層',
  },

  // --- 解決に向かうため ---
  {
    title: '本当はやりたかったことをやる',
    category: '解決に向けて',
    intensity: 3,
    tags: ['行動', '自己一致'],
    description: '本当はやりたかったことをやればいい。',
    insight: '',
    attribution: '本人',
    controllability: '可',
    timeFrame: '未来',
    depth: '表層',
  },
  {
    title: '強がっていた・けれど苦しんでいた自分を受け止める・許す',
    category: '解決に向けて',
    intensity: 3,
    tags: ['自己受容', '許し'],
    description: 'ずっと強がっていた、でも確かに苦しんでいた自分を受け止める。許す。',
    insight: '',
    attribution: '本人',
    controllability: '可',
    timeFrame: '現在',
    depth: '核心',
  },
  {
    title: '比較ではない場所／別レイヤーへ',
    category: '解決に向けて',
    intensity: 3,
    tags: ['別レイヤー', '脱比較'],
    description: '比較ではない場所に行く。別レイヤー。',
    insight: '',
    attribution: '本人',
    controllability: '可',
    timeFrame: '未来',
    depth: '中層',
  },
];

// 理由ネットワークのサンプル。
// seedTitle: 上のサンプル記録の title と一致していると、その記録に紐付く。
// parents: 他の理由の key を指定すると「より深い理由」として繋がる（図解で破線）。
window.SAMPLE_REASONS = [
  {
    key: 'R_root_family',
    text: '家族との比較構造・否定の中で育ったから',
  },
  {
    key: 'R_self_worth_by_effort',
    text: '努力した分だけ価値がある、という信念',
    parents: ['R_root_family'],
  },
  {
    key: 'R_past_justification',
    text: '苦しんできた過去を意味あるものにしたい',
    parents: ['R_self_worth_by_effort'],
  },
  {
    key: 'R_fear_rejected',
    text: '本当の自分を出すと嫌われる／拒絶される恐れ',
    parents: ['R_root_family'],
  },
  {
    key: 'R_char_switch',
    text: '相手によって見せるキャラを変える習慣',
    parents: ['R_fear_rejected'],
  },

  // 紐付け
  {
    seedTitle: '人の幸せを喜べない',
    axisKey: '',
    text: '自分もやりたいのに、できていない／やっていないことを気にしているから',
    parents: ['R_self_worth_by_effort'],
  },
  {
    seedTitle: '苦しんだ時間 vs 手に入れてきた人への憎しみ',
    axisKey: 'attribution',
    text: '同じ時間を過ごしたのに、得ているものが違いすぎるのが不公平に感じる',
    parents: ['R_past_justification'],
  },
  {
    seedTitle: '努力しない人への軽蔑と、そう思う自分への嫌悪',
    axisKey: '',
    text: 'そう思わないと、これまでの自分の選択が無価値に見えてしまう',
    parents: ['R_past_justification', 'R_self_worth_by_effort'],
  },
  {
    seedTitle: '比較構造の中で「勝つ」と言いながら疲れている',
    axisKey: '',
    text: '本当は勝負に意味はないと分かっているが、降りる許可が自分に出せない',
    parents: ['R_self_worth_by_effort'],
  },
  {
    seedTitle: '人に心を開ききれない／悪口を言われている気がする',
    axisKey: 'depth',
    text: '人は私を見たら否定するはず、という前提が染み付いている',
    parents: ['R_fear_rejected', 'R_root_family'],
  },
  {
    seedTitle: '家族からの扱いが私を形成した',
    axisKey: 'depth',
    text: '比較・否定・聞いてもらえなかった経験が基盤になっている',
    parents: ['R_root_family'],
  },
  {
    seedTitle: 'できない理由1: 人目／相手でキャラを変える',
    axisKey: '',
    text: '本当の自分を見せると嫌われるかもしれない',
    parents: ['R_fear_rejected', 'R_char_switch'],
  },
  {
    seedTitle: 'できない理由2: キャラ被り回避／先をゆく',
    axisKey: '',
    text: '人と同じでは埋もれる／価値が無い、という不安',
    parents: ['R_self_worth_by_effort', 'R_char_switch'],
  },
  {
    seedTitle: '圧倒的になるための準備中（本当の私は知られていない）',
    axisKey: '',
    text: '今の自分では不十分で、圧倒的にならないと肯定されないという信念',
    parents: ['R_self_worth_by_effort', 'R_fear_rejected'],
  },
  {
    seedTitle: '強がっていた・けれど苦しんでいた自分を受け止める・許す',
    axisKey: 'depth',
    text: '強がらなくてもここにいていい、という許可を自分に出す',
    parents: [],
  },
  {
    seedTitle: '比較ではない場所／別レイヤーへ',
    axisKey: '',
    text: '同じ土俵にいる限り終わらない。別の評価軸の場所に移ることで勝負そのものから降りられる',
    parents: [],
  },
];

